#!/usr/bin/env php
<?php 
/*
 *---------------------------------------------------------------
 * Jane runner
 *---------------------------------------------------------------
 *
 * This is the jane command line interface
 */

use Jane\Jane; 

// we dont need the first argument
array_shift( $argv );

// if no more arguments are left print out the help
if ( empty( $argv ) ) 
{
    echo 
"
+--------------------------------+
| Jane, the programming language |
+--------------------------------+

 - transform jane code to the target language
   php jane transform <file> <language:php>

"; die;
}

require 'vendor/autoload.php';

$command = array_shift( $argv );

if ( $command == 'transform' ) 
{
    echo Jane::transform( file_get_contents( array_shift( $argv ) ) ); 
}
else
{
    echo "Unknown command '".$command."'\n";
}